"use client";

import { motion } from "framer-motion";
import { FileText, Monitor, Mic } from "lucide-react";
import Link from "next/link";

const features = [
  {
    icon: <FileText className="w-8 h-8 text-white" />,
    title: "Resume Preparation",
    desc: "AI-powered ATS optimization and cinematic design for your professional profile.",
    link: "/dashboard/resume",
    delay: 0,
  },
  {
    icon: <Monitor className="w-8 h-8 text-white" />,
    title: "Portfolio Preparation",
    desc: "Showcase your expertise with stunning, interactive portfolio websites generated by AI.",
    link: "/dashboard/portfolio",
    delay: 0.1,
  },
  {
    icon: <Mic className="w-8 h-8 text-white" />,
    title: "Interview Help Services",
    desc: "Practice with our AI coach featuring real-time voice, chat feedback, and sentiment analysis.",
    link: "/dashboard/interview",
    delay: 0.2,
  },
];

export default function FeaturesSection() {
  return (
    <section id="features" className="py-32 relative z-10">
      <div className="max-w-6xl mx-auto px-6">
        <div className="text-center mb-20">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className="text-4xl md:text-5xl font-bold mb-4"
          >
            Award-Winning <span className="text-gradient">Career Services.</span>
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, delay: 0.1 }}
            className="text-xl text-text-muted"
          >
            Premium AI-driven solutions to help you land your dream role with confidence.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feature, idx) => (
            <Link key={idx} href={feature.link}>
              <motion.div
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: feature.delay }}
                className="glass-card p-10 group cursor-pointer hover:border-primary-indigo/40 hover:bg-white/[0.03] transition-all h-full"
              >
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-indigo/30 to-accent-cyan/10 border border-primary-indigo/20 flex items-center justify-center mb-8 group-hover:scale-110 group-hover:bg-primary-indigo/40 transition-all duration-300">
                  {feature.icon}
                </div>
                <h3 className="text-2xl font-semibold mb-4 text-white group-hover:text-primary-indigo transition-colors">
                  {feature.title}
                </h3>
                <p className="text-text-muted leading-relaxed">
                  {feature.desc}
                </p>
                <div className="mt-8 flex items-center gap-2 text-xs font-bold text-accent-cyan opacity-0 group-hover:opacity-100 transition-all -translate-x-2 group-hover:translate-x-0 tracking-widest uppercase">
                   Launch Engine <span>→</span>
                </div>
              </motion.div>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}
